apiVersion: apps/v1
kind: Deployment
metadata:
  name: Grab
  labels:
    app: Grab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Grab
  template:
    metadata:
      labels:
        app: Grab
    spec:
      containers:
        - name: Grab
          image: username/Grab:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5