apiVersion: apps/v1
kind: Deployment
metadata:
  name: Allocation
  labels:
    app: Allocation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Allocation
  template:
    metadata:
      labels:
        app: Allocation
    spec:
      containers:
        - name: Allocation
          image: username/Allocation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5